/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mod_16_27 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    
    case (alufn[0+5-:6])
      6'h07: begin
        if (a < b) begin
          out = a;
        end else begin
          out = a - (a / b) * b;
        end
      end
      default: begin
        out = 1'h0;
      end
    endcase
  end
endmodule
