/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alumux_1 (
    input [15:0] mole,
    input [15:0] score,
    input [15:0] molemod,
    input [15:0] scoreaddc,
    input asel,
    input bsel,
    output reg [15:0] out
  );
  
  
  
  wire [4-1:0] M_alu_first;
  wire [4-1:0] M_alu_second;
  wire [4-1:0] M_alu_third;
  wire [4-1:0] M_alu_fourth;
  wire [16-1:0] M_alu_out;
  wire [1-1:0] M_alu_z;
  wire [1-1:0] M_alu_v;
  wire [1-1:0] M_alu_n;
  wire [8-1:0] M_alu_led;
  reg [16-1:0] M_alu_a;
  reg [16-1:0] M_alu_b;
  reg [6-1:0] M_alu_alufn;
  combinedALU_12 alu (
    .a(M_alu_a),
    .b(M_alu_b),
    .alufn(M_alu_alufn),
    .first(M_alu_first),
    .second(M_alu_second),
    .third(M_alu_third),
    .fourth(M_alu_fourth),
    .out(M_alu_out),
    .z(M_alu_z),
    .v(M_alu_v),
    .n(M_alu_n),
    .led(M_alu_led)
  );
  
  always @* begin
    M_alu_a = 1'h0;
    M_alu_b = 1'h0;
    M_alu_alufn = 6'h00;
    out = 1'h0;
    if (asel == 1'h0 && bsel == 1'h0) begin
      M_alu_a = score;
      M_alu_b = scoreaddc;
      M_alu_alufn = 6'h00;
      out = M_alu_out;
    end else begin
      if (asel == 1'h1 && bsel == 1'h1) begin
        M_alu_a = mole;
        M_alu_b = molemod;
        M_alu_alufn = 6'h07;
        out = M_alu_out;
      end
    end
  end
endmodule
