/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module pushButton_11 (
    input clk,
    input rst,
    input [7:0] button,
    output reg [7:0] button_pressed
  );
  
  
  
  wire [1-1:0] M_button0_cond_out;
  reg [1-1:0] M_button0_cond_in;
  button_conditioner_14 button0_cond (
    .clk(clk),
    .in(M_button0_cond_in),
    .out(M_button0_cond_out)
  );
  wire [1-1:0] M_button0_edge_out;
  reg [1-1:0] M_button0_edge_in;
  edge_detector_7 button0_edge (
    .clk(clk),
    .in(M_button0_edge_in),
    .out(M_button0_edge_out)
  );
  wire [1-1:0] M_button1_cond_out;
  reg [1-1:0] M_button1_cond_in;
  button_conditioner_14 button1_cond (
    .clk(clk),
    .in(M_button1_cond_in),
    .out(M_button1_cond_out)
  );
  wire [1-1:0] M_button1_edge_out;
  reg [1-1:0] M_button1_edge_in;
  edge_detector_7 button1_edge (
    .clk(clk),
    .in(M_button1_edge_in),
    .out(M_button1_edge_out)
  );
  wire [1-1:0] M_button2_cond_out;
  reg [1-1:0] M_button2_cond_in;
  button_conditioner_14 button2_cond (
    .clk(clk),
    .in(M_button2_cond_in),
    .out(M_button2_cond_out)
  );
  wire [1-1:0] M_button2_edge_out;
  reg [1-1:0] M_button2_edge_in;
  edge_detector_7 button2_edge (
    .clk(clk),
    .in(M_button2_edge_in),
    .out(M_button2_edge_out)
  );
  wire [1-1:0] M_button3_cond_out;
  reg [1-1:0] M_button3_cond_in;
  button_conditioner_14 button3_cond (
    .clk(clk),
    .in(M_button3_cond_in),
    .out(M_button3_cond_out)
  );
  wire [1-1:0] M_button3_edge_out;
  reg [1-1:0] M_button3_edge_in;
  edge_detector_7 button3_edge (
    .clk(clk),
    .in(M_button3_edge_in),
    .out(M_button3_edge_out)
  );
  wire [1-1:0] M_button4_cond_out;
  reg [1-1:0] M_button4_cond_in;
  button_conditioner_14 button4_cond (
    .clk(clk),
    .in(M_button4_cond_in),
    .out(M_button4_cond_out)
  );
  wire [1-1:0] M_button4_edge_out;
  reg [1-1:0] M_button4_edge_in;
  edge_detector_7 button4_edge (
    .clk(clk),
    .in(M_button4_edge_in),
    .out(M_button4_edge_out)
  );
  wire [1-1:0] M_button5_cond_out;
  reg [1-1:0] M_button5_cond_in;
  button_conditioner_14 button5_cond (
    .clk(clk),
    .in(M_button5_cond_in),
    .out(M_button5_cond_out)
  );
  wire [1-1:0] M_button5_edge_out;
  reg [1-1:0] M_button5_edge_in;
  edge_detector_7 button5_edge (
    .clk(clk),
    .in(M_button5_edge_in),
    .out(M_button5_edge_out)
  );
  wire [1-1:0] M_button6_cond_out;
  reg [1-1:0] M_button6_cond_in;
  button_conditioner_14 button6_cond (
    .clk(clk),
    .in(M_button6_cond_in),
    .out(M_button6_cond_out)
  );
  wire [1-1:0] M_button6_edge_out;
  reg [1-1:0] M_button6_edge_in;
  edge_detector_7 button6_edge (
    .clk(clk),
    .in(M_button6_edge_in),
    .out(M_button6_edge_out)
  );
  wire [1-1:0] M_button7_cond_out;
  reg [1-1:0] M_button7_cond_in;
  button_conditioner_14 button7_cond (
    .clk(clk),
    .in(M_button7_cond_in),
    .out(M_button7_cond_out)
  );
  wire [1-1:0] M_button7_edge_out;
  reg [1-1:0] M_button7_edge_in;
  edge_detector_7 button7_edge (
    .clk(clk),
    .in(M_button7_edge_in),
    .out(M_button7_edge_out)
  );
  
  always @* begin
    M_button0_cond_in = button[0+0-:1];
    M_button0_edge_in = M_button0_cond_out;
    M_button1_cond_in = button[1+0-:1];
    M_button1_edge_in = M_button1_cond_out;
    M_button2_cond_in = button[2+0-:1];
    M_button2_edge_in = M_button2_cond_out;
    M_button3_cond_in = button[3+0-:1];
    M_button3_edge_in = M_button3_cond_out;
    M_button4_cond_in = button[4+0-:1];
    M_button4_edge_in = M_button4_cond_out;
    M_button5_cond_in = button[5+0-:1];
    M_button5_edge_in = M_button5_cond_out;
    M_button6_cond_in = button[6+0-:1];
    M_button6_edge_in = M_button6_cond_out;
    M_button7_cond_in = button[7+0-:1];
    M_button7_edge_in = M_button7_cond_out;
    button_pressed[0+0-:1] = M_button0_edge_out;
    button_pressed[1+0-:1] = M_button1_edge_out;
    button_pressed[2+0-:1] = M_button2_edge_out;
    button_pressed[3+0-:1] = M_button3_edge_out;
    button_pressed[4+0-:1] = M_button4_edge_out;
    button_pressed[5+0-:1] = M_button5_edge_out;
    button_pressed[6+0-:1] = M_button6_edge_out;
    button_pressed[7+0-:1] = M_button7_edge_out;
  end
endmodule
