/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module lfsr_randomizer_9 (
    input clk,
    input rst,
    input ctr,
    output reg [7:0] result_8bit
  );
  
  
  
  reg [7:0] M_count_d, M_count_q = 1'h0;
  
  always @* begin
    M_count_d = M_count_q;
    
    result_8bit[0+0-:1] = M_count_q[0+0-:1];
    M_count_d[1+0-:1] = M_count_q[0+0-:1];
    result_8bit[1+0-:1] = M_count_q[1+0-:1];
    M_count_d[2+0-:1] = M_count_q[1+0-:1];
    result_8bit[2+0-:1] = M_count_q[2+0-:1];
    M_count_d[3+0-:1] = M_count_q[2+0-:1];
    result_8bit[3+0-:1] = M_count_q[3+0-:1];
    M_count_d[4+0-:1] = M_count_q[3+0-:1];
    result_8bit[4+0-:1] = M_count_q[4+0-:1];
    M_count_d[5+0-:1] = M_count_q[4+0-:1];
    result_8bit[5+0-:1] = M_count_q[5+0-:1];
    M_count_d[6+0-:1] = M_count_q[5+0-:1];
    result_8bit[6+0-:1] = M_count_q[6+0-:1];
    M_count_d[7+0-:1] = M_count_q[6+0-:1];
    result_8bit[7+0-:1] = M_count_q[7+0-:1];
    M_count_d[0+0-:1] = M_count_q[7+0-:1] ~^ M_count_q[5+0-:1] ~^ M_count_q[4+0-:1] ~^ M_count_q[3+0-:1];
  end
  
  always @(posedge ctr) begin
    if (rst == 1'b1) begin
      M_count_q <= 1'h0;
    end else begin
      M_count_q <= M_count_d;
    end
  end
  
endmodule
